/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PokemonCard: typeof import('./components/PokemonCard.vue')['default']
    PokemonList: typeof import('./components/PokemonList.vue')['default']
  }
}
